# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sysMon.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1142, 347)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.USOCPULABEL_8 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_8.setGeometry(QtCore.QRect(60, 280, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_8.setFont(font)
        self.USOCPULABEL_8.setObjectName(_fromUtf8("USOCPULABEL_8"))
        self.USOCPULABEL_7 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_7.setGeometry(QtCore.QRect(60, 240, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_7.setFont(font)
        self.USOCPULABEL_7.setObjectName(_fromUtf8("USOCPULABEL_7"))
        self.USOCPULABEL_6 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_6.setGeometry(QtCore.QRect(60, 200, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_6.setFont(font)
        self.USOCPULABEL_6.setObjectName(_fromUtf8("USOCPULABEL_6"))
        self.USOCPULABEL_4 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_4.setGeometry(QtCore.QRect(60, 120, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_4.setFont(font)
        self.USOCPULABEL_4.setObjectName(_fromUtf8("USOCPULABEL_4"))
        self.gpuNome = QtGui.QLabel(self.centralwidget)
        self.gpuNome.setGeometry(QtCore.QRect(200, 240, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gpuNome.setFont(font)
        self.gpuNome.setObjectName(_fromUtf8("gpuNome"))
        self.numCores = QtGui.QLabel(self.centralwidget)
        self.numCores.setGeometry(QtCore.QRect(200, 160, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numCores.setFont(font)
        self.numCores.setObjectName(_fromUtf8("numCores"))
        self.USOCPULABEL_2 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_2.setGeometry(QtCore.QRect(80, 60, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_2.setFont(font)
        self.USOCPULABEL_2.setObjectName(_fromUtf8("USOCPULABEL_2"))
        self.USOCPULABEL_5 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_5.setGeometry(QtCore.QRect(60, 160, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_5.setFont(font)
        self.USOCPULABEL_5.setObjectName(_fromUtf8("USOCPULABEL_5"))
        self.totalRam = QtGui.QLabel(self.centralwidget)
        self.totalRam.setGeometry(QtCore.QRect(200, 200, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalRam.setFont(font)
        self.totalRam.setObjectName(_fromUtf8("totalRam"))
        self.so = QtGui.QLabel(self.centralwidget)
        self.so.setGeometry(QtCore.QRect(200, 280, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.so.setFont(font)
        self.so.setObjectName(_fromUtf8("so"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 80, 761, 221))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.nomeProcessador = QtGui.QLabel(self.centralwidget)
        self.nomeProcessador.setGeometry(QtCore.QRect(200, 120, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nomeProcessador.setFont(font)
        self.nomeProcessador.setObjectName(_fromUtf8("nomeProcessador"))
        self.MEMORIALIVRELABEL = QtGui.QLabel(self.centralwidget)
        self.MEMORIALIVRELABEL.setGeometry(QtCore.QRect(820, 200, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MEMORIALIVRELABEL.setFont(font)
        self.MEMORIALIVRELABEL.setObjectName(_fromUtf8("MEMORIALIVRELABEL"))
        self.USOMEMORIALABEL = QtGui.QLabel(self.centralwidget)
        self.USOMEMORIALABEL.setGeometry(QtCore.QRect(820, 160, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOMEMORIALABEL.setFont(font)
        self.USOMEMORIALABEL.setObjectName(_fromUtf8("USOMEMORIALABEL"))
        self.USOCPULABEL_3 = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL_3.setGeometry(QtCore.QRect(880, 60, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL_3.setFont(font)
        self.USOCPULABEL_3.setObjectName(_fromUtf8("USOCPULABEL_3"))
        self.memLivreBar = QtGui.QProgressBar(self.centralwidget)
        self.memLivreBar.setGeometry(QtCore.QRect(960, 200, 158, 21))
        self.memLivreBar.setProperty("value", 24)
        self.memLivreBar.setObjectName(_fromUtf8("memLivreBar"))
        self.USOCPULABEL = QtGui.QLabel(self.centralwidget)
        self.USOCPULABEL.setGeometry(QtCore.QRect(820, 120, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USOCPULABEL.setFont(font)
        self.USOCPULABEL.setObjectName(_fromUtf8("USOCPULABEL"))
        self.usoCpuBar = QtGui.QProgressBar(self.centralwidget)
        self.usoCpuBar.setGeometry(QtCore.QRect(960, 120, 158, 21))
        self.usoCpuBar.setProperty("value", 24)
        self.usoCpuBar.setObjectName(_fromUtf8("usoCpuBar"))
        self.usoDiscoBar = QtGui.QProgressBar(self.centralwidget)
        self.usoDiscoBar.setGeometry(QtCore.QRect(960, 240, 158, 21))
        self.usoDiscoBar.setProperty("value", 24)
        self.usoDiscoBar.setObjectName(_fromUtf8("usoDiscoBar"))
        self.usoMemBar = QtGui.QProgressBar(self.centralwidget)
        self.usoMemBar.setGeometry(QtCore.QRect(960, 160, 158, 21))
        self.usoMemBar.setProperty("value", 24)
        self.usoMemBar.setObjectName(_fromUtf8("usoMemBar"))
        self.MEMORIALIVRELABEL_2 = QtGui.QLabel(self.centralwidget)
        self.MEMORIALIVRELABEL_2.setGeometry(QtCore.QRect(820, 240, 910, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MEMORIALIVRELABEL_2.setFont(font)
        self.MEMORIALIVRELABEL_2.setObjectName(_fromUtf8("MEMORIALIVRELABEL_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(800, 80, 321, 221))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SysMonitor", None))
        self.USOCPULABEL_8.setText(_translate("MainWindow", "Sys Operacional:", None))
        self.USOCPULABEL_7.setText(_translate("MainWindow", "GPU:", None))
        self.USOCPULABEL_6.setText(_translate("MainWindow", "Memoria Ram:", None))
        self.USOCPULABEL_4.setText(_translate("MainWindow", "Processador:", None))
        self.gpuNome.setText(_translate("MainWindow", "GPU NAME", None))
        self.numCores.setText(_translate("MainWindow", "PROC Cores", None))
        self.USOCPULABEL_2.setText(_translate("MainWindow", "Configuração do Sistema", None))
        self.USOCPULABEL_5.setText(_translate("MainWindow", "Numero de Cores:", None))
        self.totalRam.setText(_translate("MainWindow", "MEM RAM", None))
        self.so.setText(_translate("MainWindow", "SO", None))
        self.nomeProcessador.setText(_translate("MainWindow", "PROC", None))
        self.MEMORIALIVRELABEL.setText(_translate("MainWindow", "Memoria Livre:", None))
        self.USOMEMORIALABEL.setText(_translate("MainWindow", "Uso da Memoria:", None))
        self.USOCPULABEL_3.setText(_translate("MainWindow", "Status do Sistema", None))
        self.USOCPULABEL.setText(_translate("MainWindow", "Uso da CPU:", None))
        self.MEMORIALIVRELABEL_2.setText(_translate("MainWindow", "Uso de disco:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

